In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
gcn_raw = pd.read_csv("hyperparameter_search_results_gcn.csv")

In [3]:
# Rows with same model,learning_rate,epochs,hidden_dim,num_layers,dropout columns values group together
gcn_grouped = gcn_raw.groupby(['model', 'learning_rate', 'epochs', 'hidden_dim', 'num_layers', 'dropout']).mean().reset_index()
# Number of rows
print(f"Number of unique hyperparameter combinations: {gcn_grouped.shape[0]}")

Number of unique hyperparameter combinations: 192

In [4]:
# Sort by val_loss and take top 10
top_10 = gcn_grouped.nsmallest(10, 'val_loss')
print("Top 10 hyperparameter combinations by validation loss:")
display(top_10)

Top 10 hyperparameter combinations by validation loss:

,model,learning_rate,epochs,hidden_dim,num_layers,dropout,train_loss,val_loss
172,gcn,0.001,300,16,3,0.0,0.004738,0.005694
189,gcn,0.001,300,32,4,0.1,0.004930,0.005711
140,gcn,0.001,200,32,4,0.0,0.004613,0.005714
185,gcn,0.001,300,32,3,0.1,0.005061,0.005742
137,gcn,0.001,200,32,3,0.1,0.005213,0.005774
142,gcn,0.001,200,32,4,0.2,0.005690,0.005791
168,gcn,0.001,300,16,2,0.0,0.004969,0.005818
141,gcn,0.001,200,32,4,0.1,0.005233,0.005838
180,gcn,0.001,300,32,2,0.0,0.004700,0.005856
177,gcn,0.001,300,16,4,0.1,0.005447,0.005857

In [5]:
graphsage_raw = pd.read_csv("hyperparameter_search_results_graph_sage.csv")

In [6]:
graphsage_grouped = graphsage_raw.groupby(['model', 'learning_rate', 'epochs', 'hidden_dim', 'num_layers', 'dropout']).mean().reset_index()

In [8]:
# Sort by val_loss and take top 10
top_10 = graphsage_grouped.nsmallest(10, 'val_loss')
print("Top 10 hyperparameter combinations by validation loss:")
display(top_10)

Top 10 hyperparameter combinations by validation loss:

,model,learning_rate,epochs,hidden_dim,num_layers,dropout,train_loss,val_loss
186,graph_sage,0.001,300,32,3,0.2,0.005213,0.005584
142,graph_sage,0.001,200,32,4,0.2,0.005565,0.005653
138,graph_sage,0.001,200,32,3,0.2,0.005690,0.005665
190,graph_sage,0.001,300,32,4,0.2,0.005200,0.005669
182,graph_sage,0.001,300,32,2,0.2,0.005344,0.005725
185,graph_sage,0.001,300,32,3,0.1,0.004894,0.005727
134,graph_sage,0.001,200,32,2,0.2,0.005664,0.005747
178,graph_sage,0.001,300,16,4,0.2,0.006232,0.005750
177,graph_sage,0.001,300,16,4,0.1,0.005467,0.005786
191,graph_sage,0.001,300,32,4,0.5,0.006505,0.005794

In [9]:
gat_raw = pd.read_csv("hyperparameter_search_results_gat.csv")

In [10]:
gat_grouped = gat_raw.groupby(['model', 'learning_rate', 'epochs', 'hidden_dim', 'num_layers', 'dropout']).mean().reset_index()

In [11]:
# Sort by val_loss and take top 10
top_10 = gat_grouped.nsmallest(10, 'val_loss')
print("Top 10 hyperparameter combinations by validation loss:")
display(top_10)

Top 10 hyperparameter combinations by validation loss:

,model,learning_rate,epochs,hidden_dim,num_layers,dropout,train_loss,val_loss
165,gat,0.001,300,8,4,0.1,0.005767,0.005834
190,gat,0.001,300,32,4,0.2,0.005211,0.005886
142,gat,0.001,200,32,4,0.2,0.005742,0.005969
176,gat,0.001,300,16,4,0.0,0.004343,0.006028
178,gat,0.001,300,16,4,0.2,0.005746,0.006053
160,gat,0.001,300,8,3,0.0,0.005130,0.006090
120,gat,0.001,200,16,2,0.0,0.005538,0.006096
116,gat,0.001,200,8,4,0.0,0.005253,0.006139
177,gat,0.001,300,16,4,0.1,0.005135,0.006141
180,gat,0.001,300,32,2,0.0,0.005263,0.006167